package org.kie.examples.phreak.grouping

import org.kie.examples.phreak.domain.Account
import org.kie.examples.phreak.domain.Account.Category
import org.kie.examples.phreak.domain.Transaction
import org.kie.examples.phreak.domain.Person

dialect "mvel"

rule gold_account
salience 200
agenda-group "gold"
when
  account: Account()
  Number(this >= 50000) from accumulate(t: Transaction(source == account); sum(t.amount))
  //Person(this == account.owner, name == "Egon")
  Number(this >= 50000) from accumulate(t: Transaction(target == account); sum(t.amount))
then
  System.out.println("Gold account: " + account);
end

rule silver_account
salience 100
agenda-group "silver"
when
  account: Account()
  Number(this >= 25000) from accumulate(t: Transaction(source == account); sum(t.amount))
  //Person(this == account.owner, name == "Egon")
  Number(this >= 25000) from accumulate(t: Transaction(target == account); sum(t.amount))
then
  System.out.println("Silver account: " + account);
end

rule bronze_account
salience 50
agenda-group "bronze"
when
  account: Account()
  Number(this >= 10000 && this < 25000) from accumulate(t: Transaction(source == account); sum(t.amount))
  //Person(this == account.owner, name == "Egon")
  Number(this >= 10000 && this < 25000) from accumulate(t: Transaction(target == account); sum(t.amount))
then
  System.out.println("Bronze account: " + account);
end
